platform :ios, '8.0'

target 'XHDemo' do
    
    pod 'SDWebImage', '~> 3.8.1'
    pod 'AFNetworking', '~> 3.1.0'
    
    pod 'SDAutoLayout', '~> 2.1.1'
    pod 'Masonry', '~> 1.0.2'
    pod 'CocoaLumberjack’, '~> 3.0.0'
    
end
